import { Suspense } from "react";
import Header from "@/components/layouts/Header";
import { Shell } from "@/components/layouts/Shell";
import { formatPrice } from "@/lib/utils";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { AddProductToCartForm } from "@/features/carts";

import {
  BuyNowButton,
  ProductCard,
  ProductImageShowcase,
} from "@/features/products";
import { AddToWishListButton } from "@/features/wishlists";
import { gql } from "@/gql";
import { getClient } from "@/lib/urql";
import { Metadata } from "next";
import { notFound } from "next/navigation";

type Props = {
  params: {
    slug: string;
  };
};
export const metadata: Metadata = {
  title: `NextBot | Your Ultimate Robots Market`,
  description: "Generated by create next app",
};

const ProductDetailPageQuery = gql(/* GraphQL */ `
  query ProductDetailPageQuery($productSlug: String) {
    productsCollection(filter: { slug: { eq: $productSlug } }) {
      edges {
        node {
          id
          name
          description
          rating
          price
          tags
          ...ProductImageShowcaseFragment
          collections {
            id
            label
            slug
          }
        }
      }
    }
    recommendations: productsCollection(first: 4) {
      edges {
        node {
          id
          ...ProductCardFragment
        }
      }
    }
  }
`);

async function ProductDetailPage({ params }: Props) {
  const { data, error } = await getClient().query(ProductDetailPageQuery, {
    productSlug: params.slug as string,
  });

  if (error) {
    console.error("GraphQL Error:", error);
    return notFound();
  }

  const productNode = data.productsCollection?.edges[0]?.node;
  if (!productNode || !productNode.featuredImage) {
    console.error("Missing featured image for product:", params.slug);
    return notFound();
  }

  if (!data || !data.productsCollection || !data.productsCollection.edges)
    return notFound();

  const { id, name, description, price } =
    data.productsCollection.edges[0].node;
  return (
    <Shell>
      <div className="grid grid-cols-12 gap-x-8">
        <div className="space-y-8 relative col-span-12 md:col-span-7">
          <ProductImageShowcase data={data.productsCollection.edges[0].node} />
        </div>

        <div className="col-span-12 md:col-span-5">
          <section className="flex justify-between items-start max-w-lg">
            <div>
              <h1 className="text-4xl font-semibold tracking-wide mb-3">
                {name}
              </h1>
              <p className="text-2xl font-semibold mb-3">{`$${formatPrice(price)}`}</p>
            </div>
            <AddToWishListButton productId={id} productName={name} />
          </section>

          <section className="flex mb-8 items-end space-x-5">
            <Suspense>
              <AddProductToCartForm productId={id} />
            </Suspense>

            <BuyNowButton productId={id} />
          </section>

          <section>
            <p>{description}</p>

            <Accordion type="single" collapsible>
              <AccordionItem value="specs">
                <AccordionTrigger>
                  What payment methods do you accept?
                </AccordionTrigger>
                <AccordionContent>
                  We accept all major credit cards including Visa, Mastercard,
                  American Express, and Discover. We also support PayPal, Apple
                  Pay, Google Pay, and Shop Pay for your convenience.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="warranty">
                <AccordionTrigger>
                  How long does delivery take?
                </AccordionTrigger>
                <AccordionContent>
                  Standard delivery takes 3-5 business days within the
                  continental US. Express shipping (1-2 business days) and
                  overnight shipping options are available at checkout.
                  International delivery times vary by destination and typically
                  take 7-14 business days.
                </AccordionContent>
              </AccordionItem>

              <AccordionItem value="shipping">
                <AccordionTrigger>Shipping & Returns</AccordionTrigger>
                <AccordionContent>
                  • <strong>Free standard shipping</strong> on orders over
                  $2,000.
                  <br />
                  • In-stock robots ship within 3 business days.
                  <br />• You may return unused robots within 30 days—just keep
                  the original packaging. A 10% restocking fee applies to opened
                  units.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </section>
        </div>
      </div>

      <Header heading={`We Think You'll Love`} />

      <div className="container grid grid-cols-2 lg:grid-cols-4 gap-x-8 ">
        {data.recommendations &&
          data.recommendations.edges.map(({ node }) => (
            <ProductCard key={node.id} product={node} />
          ))}
      </div>
    </Shell>
  );
}

export default ProductDetailPage;
